# Generated by Django 4.1 on 2022-10-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ads_category_alter_ads_owner_alter_ads_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='photo',
            field=models.ImageField(upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='logo',
            field=models.ImageField(upload_to='info/'),
        ),
    ]
